src/Patat/Presentation/Read.hs

Unfortunately, pandoc doesn't seem to export its selection of drivers from file extensions (it's in `pandoc.hs` where the `main` resides). So we're down to adding extensions one by one. I'm starting with my favourite format.

Input format: add org mode

---

extra/make-man.hs

Without this, Debian package can't build the manpage (Debian uses LANG=C).

force use of UTF-8 in make-man.hs

---

Makefile

https://tests.reproducible-builds.org/debian/rb-pkg/experimental/amd64/diffoscope-results/patat.html
`patat` is not reproducible yet. Based on the timestamp (1 day) and danielsh mentoring, it seems to indicates a timezone problem.

make build reproducible with variation of TZ

---

src/Patat/Presentation/Interactive.hs

* Add an ability to move slides with PageUp and PageDown.
* Add some comments.
Signed-off-by: mr.Shu <mr@shu.io>
----------------------------------------------------
@jaspervdj I am not sure if you are OK with this, but last time I used `patat`, I noticed that `PageUp` and `PageDown` (which are the keys emitted by many laser pointers) were ignored. This PR tries to fix that.

add: Move slides with PageUp and PageDown

---

patat.cabal

In particular, this fixes the problem Stackage was having with not being able to upgrade its version of `skylighting` in nightlies.

Allow `skylighting` 0.6 to be used.

---

README.md
patat.cabal
src/Patat/Theme.hs
tests/themes.md
tests/themes.md.dump

Hi! Love your project, great upgrade from `mdp` 😁
I added RGB support colors for themes, as supported by `System.Console.ANSI`.
The format used in the configuration YAML is the following:
```markdown
---
patat:
theme:
code:   [rgb#000, onRgb#aaa]
emph:   [rgb#6af]
header: [rgb#f80]
...
I *love* `RGB`!
```
This renders as follows:
The colors are triplets of bytes, mapping `#RGB` to `0xRRGGBB`, making for a total of 4096 different colors. Having this short format is enough for the purposes of text, is shorter to write, and also avoids a memory hog / freeze when opening `patat`: since `sgrsByName` contains all different SGR modes including the RGB ones, using the full space of `#RrGgBb` would generate 16 million entries (I tried, and it just freezes while loading for a very long time).
4096 …

Add RGB support for themes

---

src/Patat/Presentation/Display.hs
src/Patat/PrettyPrint.hs

Applies the colors for the `border` attribute of the theme to the whole border instead of just the text:

Extend theme to whole border

---

src/Patat/Presentation/Display.hs

When using two levels of headers, level 1 headers become slides with a centered title.
However, #49 introduced a bug where margins are added left and right, but the number of spaces added to the left of the centered title don't account for those margins, resulting in all titles being totally off-center to the right.

Fix centered titles not being centered

---

src/Main.hs
tests/fragments.md

This fixes the issue reported in #70 by carefully crafting the input so
it yields the same output with both pandoc versions.  Since this is a
fragile process, I also added the pandoc version to `patat --version`.
This will allow us to later have separate tests per pandoc version.

Fix tests, add pandoc version to --version

---

lib/Patat/Main.hs
lib/Patat/Theme.hs

I'm currently unable to install this package via nixpkgs, because it fails to build when it gets to the Haddock stage, throwing this error:
```
lib/Patat/Main.hs:180:5: error:
parse error on input '-- | Reads a command from stdin (or from some other IO).  This will be
-- interrupted by 'killThread' when the application finishes.’
|
180 |     -- | Reads a command from stdin (or from some other IO).  This will be
|     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
```
After reading https://fintanh.github.io/posts/fishy-documentation.html, it seems the correct syntax for non-top-level doc-comments is `-- ^`.

Fix syntactically invalid doc comments

---

lib/Patat/Presentation/Display.hs
lib/Patat/Presentation/Fragment.hs
lib/Patat/Presentation/Instruction.hs
lib/Patat/Presentation/Internal.hs
lib/Patat/Presentation/Read.hs
patat.cabal
tests/golden/outputs/fragments.md.dump

Fragments deal with how content is shown piece by piece.  For example, if we
have the slide:
Foo
. . .
Bar
There are two fragments.  First, only `Foo` is visible.  When the user goes
to the next fragment, `Foo` and `Bar` are both visible.
The first implementation of fragments in patat would compute the state of
all the visible items.  In this case, that would be:
1.  `[Foo]`
2.  `[Foo, Bar]`
This does not work elegantly if you want another pass to add further fragments:
you now need to split `Foo` in multiple places (and the thunk is no longer
shared).  This PR refactors this to use "instructions" over the slide content.
For the example, these instructions would be:
1.  `Append [Foo]`
2.  `Pause`
3.  `Append [Bar]`
The `Pause`s are explicit, and indicate how many fragments are present. …

Refactor implementation of fragments.

---

lib/Patat/Presentation/Read.hs

This commit is the attempt to add more support for other markdown file
extensions without any knowledge of haskell - at all.

add: support for multiple markdown file extensions.

---

README.md

This change rephrases the section about using images in slides.

upd: Rephrasing image in slides

---

patat.cabal

On my Mac, patat would not install without bytestring>=0.11.3. I have tested that patat works with. bytestring==0.11.3 and bumped the version requirement.

Bump bytestring, tested to work on 0.11.3

---

README.md
patat.cabal

Hi there!
This is a change to fix the nixpkgs build.   
On nixpkgs `patat` was configured to use `pandoc` version 3.1.6.1, as haskell-updates still brings in 3.0.1, and the latest Stackage bump updated the `pandoc` version to 3.1.8; which in turn requires the `skylighting` version to be greater or equal to 0.14.
I checked out `skylighting`'s changelog for things that could affect patat, and tried out the executable after the bump to see it still functions.

Bump skylighting's restrictive upper bound to 0.15

---

README.md
lib/Patat/Presentation/Read.hs

The per-user patat configuration file was `$HOME/.patat.yaml`, which does not follow the XDG standard.  We now support `$XDG_CONFIG_DIRECTORY/patat/config.yaml` (typically `$XDG_CONFIG_DIRECTORY` is set to `$HOME/.config`) which is compliant with the standard.
Note that `$HOME/.patat.yaml` is still supported for backward-compatibility, but anything in `$XDG_CONFIG_DIRECTORY` takes precedence.

Read configuration from XDG standard directory

---

README.md
lib/Patat/Eval.hs
lib/Patat/Presentation/Display.hs
lib/Patat/Presentation/Settings.hs
tests/golden/inputs/eval06.md
tests/golden/outputs/eval06.md.dump

This adds a new `wrap` section to the `eval` configuration.
By default, the output is wrapped in a code block again with the original syntax highlighting.  You can customize this behaviour by setting `wrap` to:
*  `code`: the default setting.
*  `raw`: no formatting applied.
*  `rawInline`: no formatting applied and no trailing newline.
You can use `rawInline` to draw graphics.  In order to do that, for example, we could configure `kitten` code snippets to evaluate using [Kitty]'s command `icat`.  This uses the `rawInline` code setting to ensure that the resulting output is not wrapped in a code block, and the `fragment` and `replace` settings immediately replace the snippet:
---
patat:
eval:
kitten:
command: sed 's/^/kitten /' | bash
replace: true
fragment: false
wrap: rawInline
...
See, …

Add eval.wrap option

---

README.md
lib/Patat/Eval.hs
lib/Patat/Presentation/Settings.hs
tests/golden/inputs/eval07.md
tests/golden/outputs/eval07.md.dump

`wrap` is used at the top-level of settings for wrapping at a certain column, and inside `eval` to determine the type in which the result is "wrapped". Using the same name for both is confusing, so this adds `eval.container` as the new name for `eval.wrap`.  `eval.wrap` will continue to be supported for the forseeable future, but its use will be discouraged.
This also changes the values (again keeping the original ones for backwards-compat), so the complete changes to a configuration would be:
- `wrap: code` -> `container: code`
- `wrap: raw` -> `container: none`
- `wrap: rawInline` -> `container: inline`

rename eval.wrap to eval.container

---

lib/Patat/Images/WezTerm.hs
patat.cabal

Wezterm image support was not taking the terminal shape and any pane splits into account. This patch reads the dimensions through the Wezterm CLI to constrain the image dimensions to the active pane
Added deps:
- aeson-casing
- utf8-string
There was an issue where the wezterm executable was hardcoded. This could probably use a bit more refinement into a configurable option, but as it stands there is a check to determine if "wezterm" or "wezterm.exe" are found as executables on the path.
Happy to make any changes that are needed

Wezterm fixes

---

flake.lock
flake.nix
patat.cabal

Hi there! 
As said in the commit description the latest Stackage bump breaks `patat` on `haskell-updates`, so this bumps a few dependencies. As far as I can tell things work as expected, and test still pass.
Please take a look and let me know if anything needs changing, I don't know what the timeline for that draft MR is; so might just add a patch with the diff from this PR to fix things until there's a release.

Bump dependencies to work with LTS 23

---

CHANGELOG.md
lib/Patat/Eval.hs
lib/Patat/Eval/Internal.hs
lib/Patat/Presentation/Display.hs
lib/Patat/Presentation/Display/CodeBlock.hs
lib/Patat/Presentation/Internal.hs
lib/Patat/Presentation/Settings.hs
lib/Patat/Presentation/Syntax.hs
patat.cabal
tests/golden/dump.in/eval-case-insensitive.md
tests/golden/dump.out/eval-case-insensitive.md.dump

Fix case-insensitivity of class names for `eval` code blocks (#192).
Class names are case-insensitive (like in HTML), but we were treating them
as case-sensitive.
See also #191.

Fix case-insensitivity of class names
