jaspervdj/patat

src/Patat/Presentation/Interactive.hs
=> Fixed clipping after reloading

src/Patat/Theme.hs
fixes https://github.com/jaspervdj/patat/issues/12
=> add type constraint to dropTok

src/Main.hs, src/Patat/Presentation.hs, src/Patat/Presentation/Display.hs
=> Keep running even if there are errors

README.md, patat.cabal, src/Patat/Presentation.hs, src/Patat/Presentation/Display.hs, src/Patat/Presentation/Fragment.hs, src/Patat/Presentation/Interactive.hs, src/Patat/Presentation/Internal.hs, src/Patat/Presentation/Read.hs, tests/fragments.md, tests/fragments.md.dump
=> Support for fragmented slides

README.md, src/Patat/Presentation/Display.hs, src/Patat/Presentation/Interactive.hs, src/Patat/Presentation/Internal.hs, src/Patat/Presentation/Read.hs, tests/fragments.md.dump, tests/headers.md, tests/headers.md.dump, tests/slidelevel0.md, tests/slidelevel0.md.dump, tests/slidelevel1.md, tests/slidelevel1.md.dump, tests/slidelevel2.md, tests/slidelevel2.md.dump
=> Add a `slideLevel` option & autodetect it

patat.cabal, src/Main.hs, src/Patat/Images.hs, src/Patat/Images/Internal.hs, src/Patat/Images/Iterm.hs, src/Patat/Images/W3m.hs, src/Patat/Presentation/Display.hs, src/Patat/Presentation/Internal.hs
=> Experimental images support

README.md
Just a small fix for readme consistency.
=> Minor fix for syntax highlighting code block

README.md
=> README: Fix Ubuntu package link

CHANGELOG.md, patat.cabal
Closes https://github.com/jaspervdj/patat/pull/66
=> Nix Fix: bump upper bound of pandoc to fix patat for nix

README.md
See request by @nbrandaleone in #10
=> Add a syntax highlighting example to the README

lib/Patat/Presentation/Read.hs, patat.cabal, tests/haskell/Main.hs, tests/haskell/Patat/Presentation/Read/Tests.hs
=> Error out when YAML parsing fails

README.md, lib/Patat/Presentation/Display.hs, lib/Patat/Presentation/Internal.hs, tests/golden/inputs/slidenumber.md, tests/golden/outputs/slidenumber.md.dump
Hi. Since #112 wasn't touched in some time, I picked it up.
Preview of golden test output:
=> Allow hiding slide number

.github/workflows/ci.yml, lib/Patat/Presentation/Display.hs, tests/golden/inputs/issue-111.md, tests/golden/outputs/03.md.dump, tests/golden/outputs/issue-111.md.dump
=> fix: apply block quote theming to entire block

lib/Patat/Main.hs, lib/Patat/Presentation/Display.hs, lib/Patat/Presentation/Fragment.hs, lib/Patat/Presentation/Internal.hs, patat.cabal, stack.yaml, stack.yaml.lock
=> Bump dependencies

lib/Patat/Presentation/Read.hs, lib/Text/Pandoc/Extended.hs, tests/golden/inputs/plain.txt, tests/golden/outputs/plain.txt.dump
This isn't super useful on its own, it's meant to support speaker notes.
=> Add support for showing plain text files

lib/Patat/Encoding.hs, lib/Patat/EncodingFallback.hs, lib/Patat/Main.hs, lib/Patat/Presentation/Internal.hs, lib/Patat/Presentation/Read.hs, lib/Patat/Presentation/SpeakerNotes.hs, patat.cabal, tests/golden/inputs/utf8.md, tests/golden/outputs/utf8.md.dump
=> Fall back to forcing UTF-8 if decoding fails

lib/Patat/Main.hs
=> Support filenames in bash completion

README.md, lib/Patat/Main.hs, lib/Patat/Transition.hs, lib/Patat/Transition/Dissolve.hs, lib/Patat/Transition/Internal.hs, patat.cabal
https://github.com/jaspervdj/patat/assets/95501/fddc4f63-346a-49cb-98b5-9089ab92f9bb
=> add dissolve transition effect

.github/workflows/ci.yml
relates to https://github.com/jaspervdj/patat/issues/153
=> ci: add ghc 9.4.x and 9.6.x

README.md
- relates to https://github.com/Homebrew/homebrew-core/pull/154536
=> docs: add homebrew-core package entry

.github/workflows/build-and-release.yml, .github/workflows/haskell-ci.yml, .gitignore, patat.cabal, stack.yaml, stack.yaml.lock
=> Bump dependencies for GHC 9.8 etc.

CHANGELOG.md, README.md, lib/Patat/Transition.hs, lib/Patat/Transition/Matrix.hs, patat.cabal
Loosely inspired by the 1999 science fiction movie.
=> Add a `type: matrix` transition effect
